version: "3.9"  # optional since v1.27.0
services:
    backend:
        env_file: ./backend/.env.testing
        command: ["npm", "run", "docker-test"]
        depends_on: 
            db-test:
                condition: service_healthy
    db:
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
    db-test: 
        image: postgres
        depends_on: 
            db:
                condition: service_healthy
        restart: always
        ports: 
            - '5433:5432'
        env_file: ./db/test-data-transfer/postgres.env
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
        volumes: 
            - postgres-test-data:/var/lib/postgresql/data
            

    # db-data-transfer:
    #     build:
    #         context: ./db/test-data-transfer
    #     depends_on: 
    #         db-test:
    #             condition: service_healthy
    #     env_file: ./db/test-data-transfer/postgres.env

volumes: 
    postgres-test-data:


        
