version: "3.9" # optional since v1.27.0
services:
    app:
        image: roupenv/roupenv:fg-purchasing-costing-app
        environment:
            NODE_ENV: production
            DATABASE_URL: ${DATABASE_URL}
            EXCHANGE_RATE_API_KEY: ${EXCHANGE_RATE_API_KEY}
            JWTSECRET: ${JWTSECRET}
        ports:
            - "3005:3005"
        restart: unless-stopped
        depends_on:
            - db
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5455:5432"
    app-demo:
        image: roupenv/roupenv:fg-purchasing-costing-app-demo
        environment:
            NODE_ENV: production
            DATABASE_URL: ${DATABASE_URL_DEMO}
            EXCHANGE_RATE_API_KEY: ${EXCHANGE_RATE_API_KEY}
            JWTSECRET: ${JWTSECRET}

        ports:
            - "3006:3005"
        restart: unless-stopped
        depends_on:
            - db-demo
    db-demo:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}

        volumes:
            - postgres-demo-data:/var/lib/postgresql/data
        ports:
            - "5456:5432"
volumes:
    postgres-data:
    postgres-demo-data:
